### ISSUE TITLE
[Bug] NewsOn addon is giving errors. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [Lunatixz/KODI_Addons#127]
Hey there sorry for bothering you but i was trying out NewsOn today on my pc and Breaking News is giving me an error for some odd reason. I also tried NewsOn for Android but the addon is not working at all on android. If you could take look at this addon, that would be great. 

Thank you

**Comment by Lunatixz** [comment]
Download updates via my beta repository, THX
