### ISSUE TITLE
[trumptweets] longer polling delay

### ISSUE THREAD

**Issue by h3298** [Lunatixz/KODI_Addons#13]
Allow polling delay of hours, instead of 30 minutes.  If more than one tweet occurred during interval, wait for button press to dismiss and show next unread tweet.

**Comment by Lunatixz** [comment]
I'll extend wait times and include a wait for action option.

**Comment by h3298** [comment]
The pop-up cartoon graphics are pretty cool, but since Ive been using SpaceXnow on mobile to follow their Twitter activity, it has occurred to me that Kodi could use a general purpose Twitter client where the user can specify which accounts they want to monitor. =)

**Comment by Lunatixz** [comment]
I already created one.... awhile back.
https://kodi.tv/addon/scripts/twitter-tweets
