### ISSUE TITLE
kodi 19.3 pluto.tv addon by Lunatixz 1.5.3 closes kodi

### ISSUE THREAD

**Issue by beekind54** [Lunatixz/KODI_Addons#131]
when i try to enter the addon for Pluto.TV by Lunatixz 1.5.3, i always get booted out of Kodi.
I see two pluto tv addons
Pluto TV SlyGuy works fine
Pluto.TV Lunatixz boots me out of Kodi. how to uninstall it since i always get booted out of kodi when i try to access this addon?

Using Xenon Amber Kodi build
thanks to all

**Comment by Lunatixz** [comment]
Install a Kodi nightly build, the crash issue is a bug within Kodi's last release.
