### ISSUE TITLE
[pluto.tv] Addon VOD lists limited to 100 items

### ISSUE THREAD

**Issue by pdanford** [Lunatixz/KODI_Addons#134]
OS: Raspberry Pi OS
Kodi: 19.3
pluto-tv addon: 1.5.3

The Url used by the pluto.tv addon to fetch the VOD catalouge is:
```
https://api.pluto.tv/v3/vod/categories?includeItems=true&deviceType=web&sid=0abb475...
```

Putting that directly in a browser yields:
```
{
    "offset": 100,
    "page": 1,
    "totalCategories": 140,
    "totalPages": 2,
    "categories":
    [...]
```

The first problems is `"offset": 100` means the api only returned 100 of a total of 140 categories, so the pluto.tv addon can only display those 100 (40 categories are lost).

Adding `offset=1000` to the api query parameters works around that problem; so the Url becomes:

```
https://api.pluto.tv/v3/vod/categories?offset=1000&includeItems=true&deviceType=web&sid=0abb475...
```
But for that same Url request, there is a second similar problem when the items returned for a category exceed the api's default offset (really a page limit apparently) value of 100. Here's an example of one of the categories that has more items than the default 100 the api returns:

```
{
    "offset": 1000,
    "page": 1,
    "totalCategories": 140,
    "totalPages": 1,
    "categories":
    [
        {
        ...
        {,
        {
            "_id": "58e1a299dca3c3a22fbd8319",
            "name": "Most Popular Movies",
            "plutoOfficeOnly": false,
            "page": 1,
            "offset": 100,
            "totalItemsCount": 150,
            "mainCategories":
            [
                {
                    "categoryID": "618c3cc54a27070007796ab4"
                },
                {
                    "categoryID": "611436eea449220007a0039b"
                }
            ],
            "items":
            [...(list of movie item dicts)]
```

In the above case, the totalItemsCount indicates 50 items (movies) are truncated by the api (if you look that the entire json block returned for that category or look at the view mode list options in Kodi, there are only 100). 

I couldn't find much on the pluto.tv api for that type of Url (using google and inspecting their website). Is there another query parameter analogous to `offset` (which affects only the number of categories returned) but instead corresponds to `includeItems` that can be added to the Url as a work around so we don't lose those 50 movies?

Thanks!
PD

**Comment by Lunatixz** [comment]
Thanks for the info, adding to latest update!

**Comment by pdanford** [comment]
Just to update: the Video On Demand list limit problem still exists in the 1.6.1 pluto plugin (and kodi 19.4).

To reiterate the above description:

1. start pluto plugin
2. go to OnDemand -> Action
3. then left arrow to reveal View Mode side menu

"All Videos" is still capped at 100 (the rest after that are truncated).

Thanks!

**Comment by Lunatixz** [comment]
Yes, I increased the content selection limit. however, in order to increase VOD limits, It will require a new endpoint. The endpoint I'm currently using is hardcoded to the current limit. The only other API that accesses additional content requires session tokens, which would require user login... I'll work on the code when I have free time, THX.
