### ISSUE TITLE
NewsON

### ISSUE THREAD

**Issue by markosjal** [Lunatixz/KODI_Addons#135]
NewsOn is a good addon I run it successfully on LibrreElec with no issues. 

I recently however  loaned a LibreElec box to a brother and re-purposed a Mac to take its Place.

Unfortunately the NewsOn once opened and going to "local stations" causes Mac OS to open another Kodi Instance. So then I have two  Kodi instances running. If I launch a stream then stop it, I will then have three kodi instances running.

I will NOT be uploading a  log file as there is too much to sanitize between my LAN info and what you may decide to deem as an "illegal" addon. Funny how the phrase "illegal addons" gets used even when someone has no idea of someone's country or the laws of that country .

**Comment by Goldenfreddy0703** [comment]
I'm sorry I'm confused on the last part. Are you saying that NewsOn is an illegal addon?

**Comment by markosjal** [comment]
What I am saying is that i am not sending a log file because I would have to sanitize my LAN info and you would proba ly have something to say about one of my add-ons being illegal.

**Comment by Goldenfreddy0703** [comment]
Oh I see what you mean but if you go to that specific addon then it will log it. If you don't go to the specific addon then it will not log it. So if you delete your kodi log, go on kodi and go to the newson addon and find where the error is then it will log it, not any of your illegal addons. You don't have to provide a log tho, I may provide soon tho sense NewsOn was giving me errors.

**Comment by Lunatixz** [comment]
Download updates via my beta repository, THX

**Comment by markosjal** [comment]
does that mean you fixed this or just updated other stuff?

**Comment by Lunatixz** [comment]
Without a log, I can't fix the unknown... The version in my beta repo works for me.

**Comment by markosjal** [comment]
try it on a Mac. You will see

**Comment by Goldenfreddy0703** [comment]
> Without a log, I can't fix the unknown... The version in my beta repo works for me.

Hey there sorry for asking this but does your beta repo version of NewsOn work with android? I tried NewsOn on Android and i got errors when clicking on browsing states and ect. I would provide a log but i would have to get a fresh install of kodi setup and an android device and make a link to the log and stuff.
