### ISSUE TITLE
Crash on attempted install of PlutoTV from kodi Repo

### ISSUE THREAD

**Issue by slippyC** [Lunatixz/KODI_Addons#136]
When attempting to do new install  of PlutoTV and adding through Kodi Repo, selecting completely crashes Kodi.   When hovering over item to install and it gives general information it is fine, it's after clicking to bring up dialog if you want to install(never actually opens that dialog).  I attempted other addons that were right by it in the Repo with no issues bringing up install dialog.

I'm running Kodi on Firestick, newest standard(non-4k version).  I have about 2GB of space left on device, so it shouldn't be related to that.  Kodi build is 19.2.

**Comment by Lunatixz** [comment]
Kodi was released with a bug causing some plugins to crash when accessing the addon-browser.

Install a recent Kodi nightly build in order to fix. THX

**Comment by slippyC** [comment]
Thankee sir!  Alrighty, appreciate the quick response.  I heard there were issues with the newest Matrix too.  I was trying to avoid the newest, supposed, stable build.  ;)

BTW, thanks for taking out your time to make these plugins.  The reason I even updated to Matrix was because PVR IPTV Simple Client added refreshing m3u/m3u8 files(which I needed for some scripts I was working on for rebuilding m3u lists).

Gonna close issue since I'm sure what you suggest will fix it(had the plugin running on Leia).
