### ISSUE TITLE
Cannot run Pluto.tv addon with nightly build Kodi 19.3

### ISSUE THREAD

**Issue by Jean-Dom** [Lunatixz/KODI_Addons#138]
Hi,
I add the problem of the addon crashing Kodi 19.3.
Following your advice / instruction, I have downloaded a recent Kodi Beta version 19.3 dated beginning of February.
So, I was able to download your addon. It was a bit long to install, because the automatic installation reported errors for the requested sub-modules. But I have installed them individually and it was OK.
Now, when I start the addon, the menu is displayed but I cannot display anything else: I always receive an error saying that an error occured.
Please, note that the Android TV is a HK1 Max box, 4 + 64 GB, with an ARM64V8 CPU.
Find herenclosed screen copies of the installation, the erreor message and a log files. I have highlighted a section wich seems the error.
![2022-02-05_133310](https://user-images.githubusercontent.com/2264112/152642368-02ec4500-1b69-489b-8370-93202e117825.png)
![2022-02-05_122220](https://user-images.githubusercontent.com/2264112/152642370-02a8513a-a074-4a44-80b2-0d694b76224a.png)
![2022-02-05_121117](https://user-images.githubusercontent.com/2264112/152642371-939f485b-4e59-4a28-b2db-4fceeda213ad.png)
![2022-02-05_121023](https://user-images.githubusercontent.com/2264112/152642373-01aa0941-1d55-4490-8a24-db0c4440bf41.png)
![2022-02-05_120933](https://user-images.githubusercontent.com/2264112/152642374-63867a41-0eb0-4331-a15d-b8ada83f320d.png)
![2022-02-05_120848](https://user-images.githubusercontent.com/2264112/152642375-6fb5e043-7ef8-45d4-bfdd-f31f7f358240.png)
![2022-02-05_120817](https://user-images.githubusercontent.com/2264112/152642377-a66944c1-2085-422b-bafc-19989630075f.png)
![2022-02-05_120713](https://user-images.githubusercontent.com/2264112/152642378-1a95dd7f-a54e-4e68-819e-e52870f56b1a.png)
![2022-02-05_120633](https://user-images.githubusercontent.com/2264112/152642379-14eab314-9014-4697-8094-b4e89aecad25.png)
![2022-02-05_120543](https://user-images.githubusercontent.com/2264112/152642380-69cd6f1d-b1b7-4a96-92ae-e9542d19d577.png)
![2022-02-05_120451](https://user-images.githubusercontent.com/2264112/152642381-2ac4b87b-a284-43dc-9cc1-f64ce230412c.png)

**Comment by Jean-Dom** [comment]
Log file.
[kodi.log](https://github.com/Lunatixz/KODI_Addons/files/8008017/kodi.log)

**Comment by Lunatixz** [comment]
Have my beta repo installed, I'll push an update soon. THX

**Comment by Jean-Dom** [comment]
Thanks for your answer.
I am not familiar: Where can I can it?

**Comment by Jean-Dom** [comment]
Also, if you easily know the answer: I have installed the other addon (from the Kodi Team), but it does not work either.
On another machine, I had installed the Kodi Team pluto addon and the Freebox PVR addon. Both have a guide and a channel selection based on IPTV and IPTV manager. I suspect you are also doing so.
My problem was: All channels were mixed together (first channel from pluto, the second one from Freebox…).
Is there any way to separate the channels from both addons?
Thanks in advance.

**Comment by Jean-Dom** [comment]
Sorry for the typo error:
I am not familiar: Where can I FIND it?

**Comment by Lunatixz** [comment]
https://github.com/Lunatixz/KODI_Addons/raw/master/zips/repository.lunatixz/repository.lunatixz-1.1.0.zip

**Comment by Jean-Dom** [comment]
Congratulations. It works correctly, as far as I have seen.
Greta thanks to you.
I have not seen the channels in the guide. So, no problem to be mixed with the Freebox channels.
But I think it would be great to have it, with tabs to switch form one group to another (Pluto to Freebox, another one for Rakuten for instance), like pages in a books.
So, as already said, thanks to you.
Just one thing: It is a beta version. Do I have anything to do (and when) to be back to the standard version when the enhancements will be incorporated?
