### ISSUE TITLE
CBS Shows No Free Full Episodes

### ISSUE THREAD

**Issue by mspitz1** [Lunatixz/KODI_Addons#14]
The Young and the Restless , Free Episodes where loading and running perfectly then all of a sudden no longer showing any Free Episodes. CBS must have moved all Free Episodes to a different web address. they still have Free Episodes working on their Android App.
Hope this can be Fixed.
Thanks for the Great Work

**Comment by bolzak** [comment]
Just wo!ndering if episodes of The Young and the Restless will ever return to your app?  I have been a long time Kodi user and have pretty much been able to completely cut the cord with the help of apps like yours.  I sometimes use Plex and their CBS plug-in still has it so I'm wondering why yours doesn't have it any more.  Would really appreciate getting this feature back.  Thanks for your hard work

**Comment by bolzak** [comment]
I see that the CBS daytime programs (Bold & Beautiful, Y&R, etc) seem to be available again.  Thanks for addressing"latest" menu option rather than navigating to them under the "shows" option?

Thanks again!
