### ISSUE TITLE
PlayOn Browser fails because http://m.playon.tv/q.php returns multiple addresses

### ISSUE THREAD

**Issue by geekmug** [Lunatixz/KODI_Addons#15]
The output for http://m.playon.tv/q.php for me is:

``192.168.21.11:54479|192.168.22.2:54479|192.168.22.118:54479||192.168.22.3:54479|``

The first IP happens to be the correct IP (but maybe that is just because it's a sorted list), and the other IPs are old addresses that are no longer valid and are many months old, so it is unclear when or how this list ever gets pruned by PlayOn.

The code for handling this output simply deletes all of the bars instead of treating this like a list.A simple change would be to split on the bar, and then try to download the ``/data/data.xml`` file from the candidate, and use the first one that succeeds.

**Comment by Lunatixz** [comment]
Thanks, I'll update the code to accommodate lists.

**Comment by Lunatixz** [comment]
https://github.com/xbmc/repo-plugins/pull/1956

**Comment by geekmug** [comment]
I tested this out on my local network and it works perfectly, thank you!
