### ISSUE TITLE
Allow dimming the screensaver video

### ISSUE THREAD

**Issue by cappe** [Lunatixz/KODI_Addons#158]
First off, thank you for the plugin. I found it really easy to use, and currently using it in my living room Kodi setup.

If you don't mind receiving a feature request, do you think if dimming the screensaver video would be possible? It'd add a nice touch acting as a true screensaver as opposed to blasting with full brightness.

I tried to dive into the Kodi's default screensaver "Dim" to understand how it is done but didn't get too far. I believe the code responsible for dimming the screen is here https://github.com/xbmc/xbmc/blob/54779a457b5219b5b4ed3c353d056b1736a837b6/xbmc/windows/GUIWindowScreensaverDim.cpp but I'm not sure.

Happy to help however I can :) Cheers!

**Comment by Lunatixz** [comment]
Sure... Be sure to install my beta repository to receive updates.

**Comment by Lunatixz** [comment]
Done, v.1.1.3 Enjoy!

**Comment by cappe** [comment]
Wow, that's just amazing. A few hours from a request to delivery. Thank you so much, I'll be sure to install the beta repository.
