### ISSUE TITLE
uEPG unicode problem

### ISSUE THREAD

**Issue by bbaronSVK** [Lunatixz/KODI_Addons#19]
Hi,
i'm just try to make my own first EPG, but i get error:
`09:17:50.534 T:4212   ERROR: script.module.uepg-1.0.5-prepareJson, failed! 'unicode' object has no attribute 'sort' ,Traceback (most recent call last):
                                              File "C:\Users\bbaron\AppData\Roaming\Kodi\addons\script.module.uepg\default.py", line 86, in prepareJson
                                                channelItems.sort(key=lambda x:x['channelnumber'])
                                            AttributeError: 'unicode' object has no attribute 'sort'
09:17:50.534 T:4212   ERROR: script.module.uepg-1.0.5-invalid uEPG information ,None
`

Kodi (18.0-BETA1 Git:20180826-f21b477993). Platform: Windows NT x86 64-bit
ADDON: script.module.uepg v1.0.5 installed

I call it from my plugin like this:
`
epg = '[{"channelname":"AMC","channelnumber":"-1","channellogo":"http:\/\/services.data.tvprofi.cz\/images\/logo\/web-36x20\/mgm.png","isfavorite":false,"guidedata":[{"url":"","starttime":"1536294900","endtime":"1536300309","runtime":"5409","label":"Zelvi nindzove","label2":"SD","art":[{"thumb":"http:\/\/image.tmdb.org\/t\/p\/original\/g5Z3SXrRkQFSfHXTe1BSn7oM5qA.jpg"}]},{"url":"","starttime":"1536300900","endtime":"1536306307","runtime":"5407","label":"Ambiciozni blondynka","label2":"SD","art":[{"thumb":"http:\/\/image.tmdb.org\/t\/p\/original\/gGy0TvLSjqItOgLcqV1PC4ORk0U.jpg"}]},{"url":"","starttime":"1536306600","endtime":"1536312797","runtime":"6197","label":"Mily Johne","label2":"SD","art":[{"thumb":"http:\/\/image.tmdb.org\/t\/p\/original\/2Fen9XsCscjupGJUhi2zaCvOaGd.jpg"}]},{"url":"","starttime":"1536319200","endtime":"1536324146","runtime":"4946","label":"Hleda se Jackie Chan","label2":"720p","art":[{"thumb":"http:\/\/image.tmdb.org\/t\/p\/original\/j8fR9N1PmCLAJdW5ofwqYOMaXKf.jpg"}]},{"url":"","starttime":"1536324900","endtime":"1536331098","runtime":"6198","label":"Durhamsti Byci","label2":"SD","art":[{"thumb":"http:\/\/image.tmdb.org\/t\/p\/original\/wZwXLiR1cisTXaJiuBLvgkS5HWw.jpg"}]},{"url":"","starttime":"1536331500","endtime":"1536336907","runtime":"5407","label":"Ambiciozni blondynka","label2":"SD","art":[{"thumb":"http:\/\/image.tmdb.org\/t\/p\/original\/gGy0TvLSjqItOgLcqV1PC4ORk0U.jpg"}]},{"url":"","starttime":"1536344400","endtime":"1536349970","runtime":"5570","label":"Sexy party 2","label2":"SD","art":[{"thumb":"http:\/\/image.tmdb.org\/t\/p\/original\/sGX7RUBhf9i8nI3cfGHISDnAna0.jpg"}]},{"url":"","starttime":"1536359100","endtime":"1536364968","runtime":"5868","label":"Svitani","label2":"SD","art":[{"thumb":"http:\/\/image.tmdb.org\/t\/p\/original\/tlUvt6PMP4maUalDaMc7w1e6vak.jpg"}]},{"url":"","starttime":"1536369900","endtime":"1536374778","runtime":"4878","label":"South Park: Peklo na Zemi","label2":"1080p","art":[{"thumb":"http:\/\/image.tmdb.org\/t\/p\/original\/3ffIyRixcMxzSVTivwyy585N9lH.jpg"}]}]}]'
                xbmc.executebuiltin("RunScript(script.module.uepg,json=%s&refresh_path=%s&refresh_interval=%s&row_count=%s)"%(urllib.quote_plus(json.dumps(epg)),urllib.quote_plus(json.dumps(sys.argv[0]+"?mode=20")),urllib.quote_plus(json.dumps("7200")),urllib.quote_plus(json.dumps("5"))))
`

**Comment by Lunatixz** [comment]
Link to code? Appears you are not sending the proper data type.

**Comment by bbaronSVK** [comment]
https://github.com/bbaronSVK/plugin.video.stream-cinema/pull/30/commits/0062e7e66a2235871d3e8eb8ba4f09d1875f0c1f#diff-37c7adfcac617c3b1d29b59ffc8b3779R808

here is it

**Comment by bbaronSVK** [comment]
i foud it! it was double json encoded, sorry my fault.
