### ISSUE TITLE
Does not update slideshow when new videos are added to the source directory after the slideshow has started. 

### ISSUE THREAD

**Issue by Krishna-Bhattarai** [Lunatixz/KODI_Addons#2]
Hello, 

I am using a raspberry pi 3 with raspbian operating system and I have kodi v17.3 installed. I downloaded this video screensaver addon (screensaver.videosaver) and ran it after specifying settings to point to a source directory where I had some .mp4 files. The screensaver seems to run fine however, as I started adding more and more .mp4 files when the screensaver was already running, it did not pick up the new files, it only kept playing the few files that were in the directory when the addon was first started. 

What was good was if some videos were deleted (the ones that were in the directory when the slideshow first started), it immediately recognized that they were no longer present and did not play them which was good. 

Is there something we can do to fix this issue?
Please let me know if you need more information to address this. 

Sincerely,
KB

**Comment by Lunatixz** [comment]
The screensaver does not dynamically parse folders while running. Basically only the files present on start will play.

This functionality doesn't really fit within the needs of a screensaver. If you could explain your goal perhaps I can suggest a plugin that is a better fit?

**Comment by Krishna-Bhattarai** [comment]
Lunatixz,

That sounds great and exciting! I am new to addon development but I am comfortable with Python and will be able to develop something if I can get some pointers. I have started this thread https://forum.kodi.tv/showthread.php?tid=328996 as you have suggested and also this github repository to get things started. 

Looking forward to getting this done and making it an useful plugin that everyone can enjoy!

Sincerely,
KB
