### ISSUE TITLE
Plugin doesn't launch

### ISSUE THREAD

**Issue by lordairivis** [Lunatixz/KODI_Addons#20]
Pluto.tv plugin doesn't launch at all. Pops up error message saying to check credentials.

Email/password are set appropriately in the plugin settings.

Here's my [kodi.log](https://github.com/Lunatixz/KODI_Addons/files/2408356/kodi.log)

**Comment by Lunatixz** [comment]
make sure you can load www.ip-api.com/json

**Comment by lordairivis** [comment]
Because this system is a LibreELEC Kodi client, I do not have a browser installed but I was able to successfully get the content using ``curl``:

``BedPotato:~ # curl www.ip-api.com/json``
``{"as":"AS7922 Comcast Cable Communications, LLC","city":"Denver","country":"United States","countryCode":"US","isp":"Comcast Cable","lat":39.6825,"lon":-105.1568,"org":"Comcast Cable","query":"73.95.107.216","region":"CO","regionName":"Colorado","status":"success","timezone":"America/Denver","zip":"80228"}``

**Comment by Lunatixz** [comment]
Odd, can you send me a link to a full log. Please make sure debugging is enabled in both kodi and this plugin.  Thx

**Comment by lordairivis** [comment]
[kodi.log](https://github.com/Lunatixz/KODI_Addons/files/2508744/kodi.log)

I looked up ```/storage/.kodi/addons/plugin.video.plutotv/resources/lib/plutotv.py```, line 162 and tried to figure out where it was failing and saw that it was (I think) trying to access ```api.pluto.tv```, so I tried
```BedPotato:~ # curl api.pluto.tv```

and got this response:
```Cannot GET /```

Not sure if this is expected or helps any.

**Comment by Lunatixz** [comment]
For whatever reason, your device/network is not connecting to www.ip-api.com/json. If you are using a VPN or Ad blocking service please disable. THX

**Comment by cmalvado** [comment]
Hello Xumo was working until a few days ago.  Now when I click on Channels on demand or Guide it gives an error saying something went wrong.  Any fix to this?  Thanks.

**Comment by lordairivis** [comment]
> For whatever reason, your device/network is not connecting to [www.ip-api.com/json](http://www.ip-api.com/json). If you are using a VPN or Ad blocking service please disable. THX

*.ip-api.com is added to my ad blocking whitelist, and the device can bring up the contents of the page without issue. Just as a test, I disabled pfBlockerNG and verified I was able to successfully open the plugin. Afterwards, I reenabled pfBlockerNG and I can apparently load the plugin without issue now.

Thank you for the assistance.

**Comment by cmalvado** [comment]
I dont use either. I can use Pluto Tv with no problem and I was using Xumo as well.  Not certain why it stopped working. I have not changed anything. Ill try to figure this out.  Thanks for your response and excellent work.
