### ISSUE TITLE
plugin.video.plutotv: Can't search for content

### ISSUE THREAD

**Issue by LouisDK1** [Lunatixz/KODI_Addons#217]
The official Pluto.tv app and website has a new search feature where you can also find content not accessible by categories. 

As this feature is not yet available in the Kodi app  said content can't be found via the Kodi app.

**Comment by Lunatixz** [comment]
THX, definitely something I'm interested in supporting... Really busy at the moment; I'll add it to my todo list.

**Comment by SiNaPsEr0x** [comment]
Crash on 19.3 Android tv install from repository
