### ISSUE TITLE
Raspberry 2 can't be updated to higher version than 18.9 Leia

### ISSUE THREAD

**Issue by andreas1974** [Lunatixz/KODI_Addons#234]
Hi Lunatixz!

I'd really like to watch PlutoTV from the same device as I use for other on tv "play" services. However, since it's a Raspberry ver 2 it can't be updated to higher version of Kodi than 18.9 "Leia". Pluto tv is not present in the addons list. I guess it has to do with my version of Kodi, right?

Is there a way to watch Pluto.tv on my raspberry 2 with Leia Kodi?
Otherwise, I'd like to ask you if you see any possibility to make it work in a future release of your addon?

Thanks,
Andreas

**Comment by Lunatixz** [comment]
Sorry my projects always move support to the latest Kodi release.
