### ISSUE TITLE
Sling TV addon

### ISSUE THREAD

**Issue by waskodi** [Lunatixz/KODI_Addons#250]
My Sling TV addon for Kodi 20.2 does not work and I noticed that neither Nexus nor Sling were listed in your repository list.
Will you be updating a Sling addon or do you know anyone who is currently working on it?
I contacted Sling hoping they might have a clue but  hit the company wall line of ignorance.

**Comment by Lunatixz** [comment]
This project is closed, you can find recent developments here: d21spike/plugin.video.sling: Sling TV Add-On for Kodi - GitHub https://github.com/d21spike/plugin.video.sling
