### ISSUE TITLE
google.earth black screen - fail to get url

### ISSUE THREAD

**Issue by spectroman** [Lunatixz/KODI_Addons#251]
Running Kodi 20.3 on ArchLinux

Kodi was last updated at 16 Jan, but I am unsure if broken due to the update or afterwards...

At the log is seen:

```
2024-01-23 23:09:47.046 T:3646    error <general>: screensaver.google.earth-1.0.9-getURL, Failed! Expecting value: line 2 column 1 (char 1)
2024-01-23 23:09:47.050 T:3646    error <general>: screensaver.google.earth-1.0.9-setImage Failed! 'photoUrl'
```

Any ideas?

**Comment by PhoqueMicrosoft** [comment]
Same issue here running Kodi Kodi (20.1 (20.1.0) .  Clearing the cache and reinstalling the add-on had no effect. 3 machines affected.  All running windows 10 and same versions of Kodi and Python.  Issue was first reported to me Jan 22

**Comment by Lunatixz** [comment]
Looks like the google endpoint I was using is closed... for now this project is broken until I can find an alternative.

**Comment by AstonishingAston** [comment]
> Looks like the google endpoint I was using is closed... for now this project is broken until I can find an alternative.

Oh man, that's a real bummer!  My partner and I absolutely loved this on the lounge TV.

Is there anywhere or way I can follow updates on your Google Earth screensaver in hopes you're able to get it back up and running in the future?

**Comment by spectroman** [comment]
@AstonishingAston if your notifications aren't muted, you will probably hear from @Lunatixz when he have news through comments on this issue...

**Comment by ManilaByNight** [comment]
So if this add-on screensaver isn't working or always breaks then perhaps it is better to totally scrap this from the Kodi library. It is just a headache if this always has to break.

**Comment by Lunatixz** [comment]
Done! https://github.com/xbmc/repo-scripts/pull/2652
