### ISSUE TITLE
Can't open any stream

### ISSUE THREAD

**Issue by SuperDOS** [Lunatixz/KODI_Addons#26]
Running Earthcam on Kodi 18 beta 5 no streams work.

From the kodi.log:
`00:27:30.304 T:13856   ERROR: plugin.video.earthcam-1.0.2-openURL Failed! <urlopen error no host given> ,Traceback (most recent call last):
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.earthcam\resources\lib\earthcam.py", line 70, in openURL
                                                response = urllib2.urlopen(request, timeout = TIMEOUT).read()
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 427, in open
                                                req = meth(req)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 1126, in do_request_
                                                raise URLError('no host given')
                                            URLError: <urlopen error no host given>
00:27:30.671 T:4536   ERROR: Previous line repeats 4 times.
00:27:30.671 T:4536  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.earthcam/?url=http%3Ahttps%3A%2F%2Fvideos3.earthcam.com%2Ffecnetwork%2F3273.flv%2Fplaylist.m3u8&mode=9&name=Miami+Beach+-+Downtown+Miami%2C+United+States+Live+%28HLS%29
00:27:30.671 T:15972  NOTICE: Creating InputStream
00:27:30.677 T:15972 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.earthcam/?url=http%3Ahttps%3A%2F%2Fvideos3.earthcam.com%2Ffecnetwork%2F3273.flv%2Fplaylist.m3u8&mode=9&name=Miami+Beach+-+Downtown+Miami%2C+United+States+Live+%28HLS%29
00:27:30.677 T:15972   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.earthcam/?url=http%3Ahttps%3A%2F%2Fvideos3.earthcam.com%2Ffecnetwork%2F3273.flv%2Fplaylist.m3u8&mode=9&name=Miami+Beach+-+Downtown+Miami%2C+United+States+Live+%28HLS%29]
00:27:30.677 T:15972  NOTICE: CVideoPlayer::OnExit()
00:27:30.774 T:4536  NOTICE: CVideoPlayer::CloseFile()
00:27:30.774 T:4536  NOTICE: VideoPlayer: waiting for threads to exit
00:27:30.774 T:4536  NOTICE: VideoPlayer: finished waiting
`

**Comment by Lunatixz** [comment]
I'll look into it when I have some free time...
