### ISSUE TITLE
deafault.xml skin file references non-existent include 

### ISSUE THREAD

**Issue by scott967** [Lunatixz/KODI_Addons#32]
In file default.xml is an include:
`<include>contentpanelslide</include>`

but contentpanelslide is not available.

**Comment by Lunatixz** [comment]
To what are you referring? A script?

**Comment by scott967** [comment]
Skin includes have to be defined in an "include" file.  I'm assuming contentpanelslide is some sort of animation that was used in a skin (I don't see it in Estuary) so don't know what the intent is.

**Comment by Lunatixz** [comment]
Yes... I understand that. Its most likely a remnant from an older project. Could you point me to which project has the "include"?

**Comment by GwynethLlewelyn** [comment]
To me, it looks like it comes from screensaver.bing.

**Comment by Lunatixz** [comment]
THX, I'll look into it...
