### ISSUE TITLE
SimpleCache not compatible to Python 3

### ISSUE THREAD

**Issue by goggle** [Lunatixz/KODI_Addons#41]
Hi,

I've seen that you also use `script.module.simplecache` for many of your plugins. Since we should try to make our plugins work with Python 3, it would be a lot easier if the dependencies support Python 3. Unfortunately, SimpleCache does not work with Python 3, so I have opened a PR (https://github.com/kodi-community-addons/script.module.simplecache/pull/7) to make it Python 3 compatible, but did not get any response...

Do you have any idea, what we could do?

**Comment by Lunatixz** [comment]
I'll review the commit and merge...
