### ISSUE TITLE
[screensaver.google.earth] api changed

### ISSUE THREAD

**Issue by kalich9681** [Lunatixz/KODI_Addons#45]
Hi. All my kodi devices stuck with default marble canyon image. After some investigating I found out that key "nextApi" in json is no more. Looks like it replaces with "nextSlug"

I made some changes and it working now
```-             baseAPI = results['nextApi']```
```+             baseAPI = "/_api/{}.json".format(results['nextSlug'])```

**Comment by Lunatixz** [comment]
v.1.0.5 in beta repo, pending Kodi repo.
