### ISSUE TITLE
CBS InputStream Adaptive error

### ISSUE THREAD

**Issue by Arkadia2008** [Lunatixz/KODI_Addons#5]
Latest CBS version only works for me with InputStream Adaptive disabled.

Any idea why?

https://paste.kodi.tv/gogiwekebi

**Comment by Arkadia2008** [comment]
I want to use InputStream Adaptive, but CBS only works for me on Kodi 17 (Android and Windows) with InputStream Adaptive disabled.
The moment I enable InputStream Adaptive in the settings, CBS stops working.

Debug Log with InputStream Adaptive enabled:

https://paste.kodi.tv/hoxujoqoza

**Comment by Lunatixz** [comment]
Fixed v.1.0.8
