### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by avibrazil** [Lunatixz/KODI_Addons#50]
After installation and user configuration, it fails on plugin startup with a generic error suggesting to check the logs.
But there is no logs being generated. Even enabled debug mode on plugin settings.xml, but no logs being generated.

**Comment by Lunatixz** [comment]
Which Plugin are you referring to?

**Comment by stnufc** [comment]
To USTVnow, I suppose?

Live category isn't working. Which is strange. It's worked a few weeks ago...

**Comment by djzort** [comment]
Seems to be the page size in getChannelData -> https://github.com/Lunatixz/KODI_Addons/commit/5b06cb2f25a921399199fa0fc0d0b4d089dbcde6

**Comment by Lunatixz** [comment]
USTVnow will be changing their backend again.... so the plugin won't be fixed until that move is completed. THX
