### ISSUE TITLE
example and example json data causes errors and codes need correction

### ISSUE THREAD

**Issue by tingjhenjiang** [Lunatixz/KODI_Addons#51]
It took me days to solve the following problems:

1. the readme "Minimum JSON Example" link misses. (which links to (https://github.com/Lunatixz/XBMC_Addons/raw/master/script.module.uepg/resources/example.json) ) 
2. running json example you provides(which the real URL should be (https://github.com/Lunatixz/KODI_Addons/blob/master/script.module.uepg/resources/example.json) generates a lot of problems, and the correct json data structure should be as follows:

```
epgsrcdict = [{
	"channelname": "testch1",
	"channelnumber": 1,
	"channellogo": "",
	"isfavorite": "False",
	"guidedata": [{
		"url": "",
		"starttime": 0,
		"endtime": 0,
		"runtime": 0,
		"label": "",
		"label2": "HD",
		"art": {
			"thumb": "test.png"
		},
		"streamdetails": {
			"video": ""
		}
	}]
}]
epgsrcdict = json.dumps(epgsrcdict)
uepg.initChannels(params, data=epgsrcdict, dataType='json')
```
3. upeg.py line 178 code would generate errors ( '' object or empty string should not be the argument of int() )
`for idx, tmpdata in enumerate(selfchannelguidedata): totalTime = totalTime + int((tmpdata.get('runtime','') or tmpdata.get('duration','')))`
4. url paramter example is wrong where you provides json.dumps("7200”), where the numbers should not be in string type.
5. after I solve the problems mentioned above, the epg still does not show. Kodi just runs and does not stop, and I just don't know what the problem is. The error logs are something like this:

> 2020-02-20 20:31:09.312 T:17260   ERROR: CPythonInvoker(4, 
> C:\Users\TJ\AppData\Roaming\Kodi\addons\plugin.video.testvideo\addon.py): script didn't stop in 5 seconds - let's kill it
> 2020-02-20 20:31:09.312 T:17260   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.testvideo/epg/
> 2020-02-20 20:31:09.315 T:6232   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.testvideo/epg/) failed
> 2020-02-20 20:31:10.295 T:5116  NOTICE: [xbmcswift2] Request for "/" matches rule for function "index"
> 2020-02-20 20:31:12.218 T:17876  NOTICE: [xbmcswift2] Request for "/epg/" matches rule for function "list_epg"
> 2020-02-20 20:31:32.928 T:6232 WARNING: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
> 
6. Your script just won't work with the above simple epg data in json format.

**Comment by Lunatixz** [comment]
readme is outdated... yes it should be a string
