### ISSUE TITLE
script.kodi.android.update not in Matrix repo due to xbmc.python version.

### ISSUE THREAD

**Issue by lorkadiscovery** [Lunatixz/KODI_Addons#52]
script.kodi.android.update no longer shows in the Matrix repo as xbmc.python in https://github.com/Lunatixz/KODI_Addons/blob/master/script.kodi.android.update/addon.xml is not set to 3.0.0

This was discussed here https://github.com/xbmc/xbmc/issues/17326

**Comment by Lunatixz** [comment]
Thanks, This plugin was not pushed to the matrix repo as of yet. I'll prepare a proper matrix submission.

**Comment by lorkadiscovery** [comment]
Thank you for the great work you do.
