### ISSUE TITLE
script.kodi.android.update shows in Kodi Windows repository.

### ISSUE THREAD

**Issue by lorkadiscovery** [Lunatixz/KODI_Addons#53]
Hello again,

I know you will be getting sick of me by now 😂 

The android installer is showing in the Windows repository, i assume because of 
```<platform>all</platform>```
in addon.xml

Shouldnt this be
```<platform>android</platform>```

https://github.com/Lunatixz/KODI_Addons/blob/master/script.kodi.android.update/addon.xml#L15

**Comment by Lunatixz** [comment]
'Android' is the correct target platform; which it is: https://github.com/xbmc/repo-scripts/blob/jarvis/script.kodi.android.update/addon.xml#L15

However, in my beta repository, it's left 'all' so I can develop the code from any platform.

THX
