### ISSUE TITLE
News 12

### ISSUE THREAD

**Issue by dmxcasper2** [Lunatixz/KODI_Addons#54]
News 12 add-on is not working. Did maintenance on this stopped going forward?

**Comment by kekukui** [comment]
I dont see any '**News 12**' addon in the Lunatixz repo.  (I collect live news stream links and this one is news to me.  😉  Can you share a link to this addon?)

**Comment by Lunatixz** [comment]
News12 went behind a paywall, the plugin was marked broken. I noticed a few free feeds have popped up on their website. I'll look into adding them.
