### ISSUE TITLE
[Trump tweets] tweets with embedded links are truncated & missing description

### ISSUE THREAD

**Issue by kekukui** [Lunatixz/KODI_Addons#57]
![image](https://user-images.githubusercontent.com/20834957/80670667-837c7580-8a75-11ea-9eb3-3cc63cf1be66.png)

https://www.foxnews.com/politics/michael-flynn-fbi-handwritten-notes-get-him-lie-fired

----------

**Note that two different link captions are available on Twitter, for example:**

![image](https://user-images.githubusercontent.com/20834957/80671181-1b2e9380-8a77-11ea-90f6-6b1cd7dbb2fb.png)

https://twitter.com/realDonaldTrump/status/1255657225659523072?s=20

![image](https://user-images.githubusercontent.com/20834957/80671345-88422900-8a77-11ea-8a6f-a9ea4fc24467.png)

https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2FrealDonaldTrump%2Fstatus%2F1255657225659523072&widget=Tweet

**Comment by kekukui** [comment]
**It would be nice if you could display a smaller version of the embedded image with the link below it, but for a quick fix it would probably be sufficient to insert a couple of line feeds if the link is preceded by a caption like this:**

![image](https://user-images.githubusercontent.com/20834957/80744558-d6454400-8aec-11ea-9fe7-4e5c21391c07.png)

**By the way, who did the awesome art work on this addon?  Its really cool to have the character change with every tweet (and more than we expect from the typical Kodi script.)** 😁

**Comment by kekukui** [comment]
**When the link appears on the last line of the window, its illegible.  I guess you need to count the link as a separate line when deciding whether to activate scrolling.**

![screenshot002g](https://user-images.githubusercontent.com/20834957/80749634-b9147380-8af4-11ea-86dc-820f52274f02.png)

I searched for a link to this tweet so you have some way to check when the issue is fixed.  What came up first in the result was a mobile link.  I did not know this format existed since the Twitter mobile app has always required a login, but now it makes sense that they have a separate web layout for mobile user agents.  In any case, this simpler layout might be helpful if you are scraping Twitter on Kodi.  I dont think the addon is using it now because the embedded link in the screenshot above is not the same one here:

_**States, tribal, local, & territorial officials: Resources are available to help quickly identify new #COVID19 cases, break chains of transmission, and protect first responders and healthcare workers from infection.**_ **`https://bit.ly/2RLY9k9`**

https://mobile.twitter.com/realDonaldTrump/status/1254034484460244993

**Comment by Lunatixz** [comment]
I pushed an updated v.1.0.5 let me know if you are still encountering this problem. THX

**Comment by kekukui** [comment]
Too bad he is banned from Twitter now, we no longer get to enjoy this fun app - but it serves as a template for others - maybe could be repurposed for Elon Musk tweets 😁
