### ISSUE TITLE
Cannot open any Newscast [Needs Update]

### ISSUE THREAD

**Issue by Goldenfreddy0703** [Lunatixz/KODI_Addons#58]
Hey their, sorry for bothering you but your the only person who know how to provide local news with our states. Is their any chance you can update its add-on and there video api keys to there NewsOn Website. If you could, that would be great and i would be appy to have this for my full on media center.

**Comment by SHAUNP1972** [comment]
I cant be doing that hun im sorry xx

Sent from Yahoo Mail on Android 
 
  On Thu, 21 May 2020 at 2:28, Goldenfreddy0703<notifications@github.com> wrote:   


Hey their, sorry for bothering you but your the only person who know hows to provide local news with our states. Is their any chance you can update its add-on and there video api keys to there NewsOn Website. If you could, that would be great and i would be appy to have this for my full on media center.

**Comment by Goldenfreddy0703** [comment]
Aww its ok but would there by any chance an addon similar to provide local news from each state in the us?

**Comment by Lunatixz** [comment]
Newson plug-in is currently broken, I'll push a fix shortly... Thx

**Comment by Goldenfreddy0703** [comment]
Thank you so much and your the best.

**Comment by Goldenfreddy0703** [comment]
Hey there, I'm so sorry for bothering but sense about a month or two, NewsOn Discontinued the web streaming temporarily so all we have is the apps or apk'a. Sense it's been about 2 months, do you have any updates or changes you made to this addon? I know things are pretty tight and all and I understand that there are alot of addons that need to make alot of changes but will this addon be working again or will it shutdown in the future?

**Comment by Lunatixz** [comment]
I'll have a working version... However, its release is planned for Kodi Matrix.

**Comment by Goldenfreddy0703** [comment]
Dude, thank you very much and I'm so happy to hear that. I have live iptv on kodi but there was no way to get local News cast on it and this is litterly the only addon I'm waiting for. One big question I have is when do you think kodi matrix will be release?

**Comment by Lunatixz** [comment]
Submitted to Kodis repo (Matrix)
