### ISSUE TITLE
Locast Kodi add-on not working

### ISSUE THREAD

**Issue by jbumgit** [Lunatixz/KODI_Addons#63]
I'm using Kodi Leia 18.2 on a Raspbian Stretch.  I tried installing the Locast addon and entered my login info.  On running the add-on, I get an error as shown below.  The full error from kodi.log is available at https://pastebin.com/AQJP1rfb

                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded

Is this a known issue or a problem with my configuration?  Any help is appreciated.

**Comment by jbumgit** [comment]
Locast add-on version is 1.0.5

**Comment by Lunatixz** [comment]
Thanks, Locast is currently broken and will be fixed for its matrix release.
