### ISSUE TITLE
Crush from the start

### ISSUE THREAD

**Issue by af1283** [Lunatixz/KODI_Addons#68]
Videosaver crushed from the start at openelec 8.0.4. In details: i'm select a small sample mp4 video and want to see a preview. Addon chushes. 
my kodi.log about this tells
[https://bitbucket.org/screesaver-crush-log/workspace/snippets/9naeeb](url)

**Comment by Lunatixz** [comment]
You have to set a path to a file or folder... you set "library://video/" which is a root directory.
