### ISSUE TITLE
[Request] Oxygen Channel for Kodi

### ISSUE THREAD

**Issue by CHJ85** [Lunatixz/KODI_Addons#69]
Hi there. So Oxygen.com has a lot of full-length episodes of many great shows. And you don't even have to be logged in.
Do you think you could put together an Oxygen Channel kodi addon please? There used to be one a few years ago, but it obviously doesn't work anymore.
Thanks in advance.

**Comment by Lunatixz** [comment]
Thanks, Looks like an intresting site... However, until I finish porting my current projects to Matrix (PY3) I won't be taking on anything new. When the time comes I'll keep it in mind.

**Comment by CHJ85** [comment]
Of course. No rush on this.
