### ISSUE TITLE
subtitles (CC)

### ISSUE THREAD

**Issue by fondary** [Lunatixz/KODI_Addons#7]
Hi,

Thank you for the last update that fixed the streams for me.
Would it be possible to have the Closed captions visible ? It says enabled for me but nothing showing up (example Late show with Stephen Colbert, kodi 17, Win10)

Many Thanks !

**Comment by Lunatixz** [comment]
Subtitles parsing is present in most of my plugins; if you are not seeing one... most likely a compatible source wasn't found.
