### ISSUE TITLE
Please update the Pluto TV addon

### ISSUE THREAD

**Issue by CHJ85** [Lunatixz/KODI_Addons#74]
Pluto has made changes to the API.
Could you please look into this?

**Comment by Lunatixz** [comment]
PlutoTV was updated to the "new" api several months ago, The current version is working. What exactly is the issue? can you post a log?

**Comment by CHJ85** [comment]
The channels aren't showing so I'm thinking that perhaps the url structure is different.

**Comment by Lunatixz** [comment]
They are showing up on my end... I do not see any changes in the API. Log could help... pls make sure you are running the lastest copy v.1.5.1

**Comment by CHJ85** [comment]
Ah figures. I am not running the latest.
My apologies. Sorry.
