### ISSUE TITLE
PyQRCode

### ISSUE THREAD

**Issue by Ghostbird** [Lunatixz/KODI_Addons#77]
You're [listed on the wiki](https://kodi.wiki/view/Add-on:PyQRcode) as the maintainer of this script module, however I can not find it. I need to show a QR code for device authorization flow. What would you suggest I do?

Additionally the wiki shows that PyQRCode is in the Kodi Addon repositories, however it cannot be found there.

**Comment by Lunatixz** [comment]
I'll correct that now... my master branch is matrix... and was missing those modules.

**Comment by Ghostbird** [comment]
Thanks a lot!
