### ISSUE TITLE
Sky news addon on kodi 19 matrix

### ISSUE THREAD

**Issue by vecnar** [Lunatixz/KODI_Addons#79]
Hi,

I hope I am writing in correct place as i couldn't find author Lunatixz anywhere else. 
Will sky news addon be supported in kodi 19 repo?

Thank you,
Oleg

**Comment by Lunatixz** [comment]
Yes, most of my plugins are moving over to Matrix. I'll try and get to Skynews soon.

**Comment by vecnar** [comment]
Thank you for a quick reply. Do let me know if you would like me to test any on Amazon fire TV stick 4k that runs on arm 32 Kodi matrix. Just let me know where to download zip file.
Have a good day
