### ISSUE TITLE
Video Screensaver does not adjust volume on Matrix

### ISSUE THREAD

**Issue by jaydawgx7** [Lunatixz/KODI_Addons#80]
In the video screensaver settings, I have the volume set to be zero, however, I've noticed when using video screensaver on Kodi Matrix, the volume is never set and still plays at 100% whether passthru is enabled or not.

**Comment by Lunatixz** [comment]
I'll look into it; be sure to install my beta repo...

**Comment by rafalcieslak** [comment]
I can confirm this problem, it is 100% reproducible here. Setting the volume in screensaver settings to any value has no effect.

**Comment by Lunatixz** [comment]
Fixed.... v.1.1.0

**Comment by rafalcieslak** [comment]
Wow, really appreciate this response time. The fix works great on my device :+1:
