### ISSUE TITLE
Can't Install Repository

### ISSUE THREAD

**Issue by viking2** [Lunatixz/KODI_Addons#81]
Sorry for being a Newbie at this... I wanted to install NewsOn, and if I understand correctly, I must first install your Repository.
I downloaded "repository.lunatixz-1.1.0.zip" and tried to install it using "install from zip file". However, I get an error due to "incorrect structure".

Thanks in advance!

**Comment by Lunatixz** [comment]
You probably dl the link, not the file... Does the file open as a zip? if not use this link below...

https://raw.githubusercontent.com/Lunatixz/KODI_Addons/master/zips/repository.lunatixz/repository.lunatixz-1.1.0.zip

**Comment by viking2** [comment]
You are right! Somehow the link was downloaded as a zip file. Not sure how that could have happened.
I installed the repository with the correct zip file. However, it states Matrix. I am using Kodi v18.9. 
Is there some way to install NewsOn on v18.9 (I have other Add-ons and I am not sure if they will work in v19)?

**Comment by Lunatixz** [comment]
All my plugins are moving to Matrix, I won't be supplying backward support... ie. if the Leia plugin breaks it won't be fixed....

For my Leia plugins, you need my Leia repo.
https://github.com/Lunatixz/KODI_Addons/raw/master/zips/repository.lunatixz.leia/repository.lunatixz.leia-1.0.7.zip

FYI... Newson in Leia is broken!
