### ISSUE TITLE
Update: Locast.org Iconography (Icon & Fan Art)

### ISSUE THREAD

**Issue by 27hectormanuel** [Lunatixz/KODI_Addons#84]
Hi, Lunatixz

Please update the icons in the master with the official press release files, [here](https://www.locast.org/news/app/uploads/Locast_Press_Kit.zip?x29791)

In my local add-on I replaced the files with these:

![icon](https://user-images.githubusercontent.com/22853711/123070668-f36c5e80-d3e1-11eb-8d35-a5f78a3a4174.png)
![fanart](https://user-images.githubusercontent.com/22853711/123070671-f404f500-d3e1-11eb-8d28-0c8647ec89d4.jpg)

**Comment by Lunatixz** [comment]
not interested in updating the art right now... thanks for the suggestion.
