### ISSUE TITLE
Break at PTV Warning Card GSA16

### ISSUE THREAD

**Issue by Raspifan2020** [Lunatixz/KODI_Addons#85]
Hi @Lunatixz,

when I want to watch VOD streams with the Pluto.TV addon in Germany that are only from FSK 16, the message comes up briefly:

https://i.imgur.com/uFsWwsx.jpg

PTV Warning Card GSA16, and then the stream stops. But you can watch the stream via the homepage of Pluto.TV. 

For example S03 E09 Totenmesse
https://pluto.tv/de/on-demand/series/sanctuary-de/details/season/3?utm_source=google&utm_medium=textsearch&utm_campaign=1000007&utm_content=10000083&gclid=EAIaIQobChMIzZ6RmKqK8gIVBG8YCh2zFA40EAAYASAAEgJig_D_BwE

Can you change this?

Thanks for this great addon!

**Comment by Lunatixz** [comment]
Thx, responded in Kodi forum, I'll look into it...
